version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ecs-demo:2
        LoadBalancerInfo:
          ContainerName: "mydemo"
          ContainerPort: 80

